version: 0.2
env:
  variables:
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_ORGANIZATION: "tonchan1216"
    SONAR_PROJECT_KEY: "lesson5_common"
  parameter-store:
    SONAR_LOGIN: "ma-furutanito-sonar-password"
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn -f common/pom.xml package sonar:sonar -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_LOGIN} -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.organization=${SONAR_ORGANIZATION}
artifacts:
  files:
    - common/target/lesson5-common-0.0.1-SNAPSHOT.jar
